Repository jsdcommunity/build_Together_Freelacing-site-for-Developers_BackEnd, pull requests merged in 2021-11, with the labels that each got.

#16 Added `Available commands to development` section in README.md
  README.md
Labels: documentation, in-review, awaiting-review

#17 Update user new token
  controllers/index.js
  helpers/index.js
  middlewares/validations/userValidation.js
  routes/index.js
Labels: in-review, awaiting-review, improvment

#18 Get user router
  controllers/index.js
  helpers/index.js
  routes/index.js
Labels: enhancement

#19 Code formatted
  controllers/index.js
Labels: improvment

#20 ObjectId validation added in `get-user` router
  controllers/index.js
Labels: bug, in-review, awaiting-review, improvment

#21 `create-job` router finished
  controllers/buyerControllers.js
  controllers/index.js
  helpers/buyerHelpers.js
  helpers/index.js
  middlewares/index.js
  middlewares/validations/jobValidation.js
  middlewares/validations/userValidation.js
  models/job.js
  routes/buyer.js
Labels: enhancement, awaiting-review

#22 Completed : `get-jobs` router
  controllers/index.js
  helpers/index.js
  routes/index.js
Labels: enhancement

#25 POST `create-proposal` router created
  controllers/buyerControllers.js
  controllers/developerControllers.js
  controllers/index.js
  helpers/developerHelpers.js
  helpers/index.js
  middlewares/validations/proposalValidation.js
  models/proposal.js
  routes/developer.js
Labels: enhancement, awaiting-review

#30 Get created job requirements by an individual buyer
  controllers/buyerControllers.js
  helpers/buyerHelpers.js
  routes/buyer.js
Labels: enhancement

#29 Get created proposals by an individual developer
  controllers/developerControllers.js
  helpers/developerHelpers.js
  routes/developer.js
Labels: enhancement

#27 Fixed : developer can't create multiple job proposal on one job requirement
  controllers/developerControllers.js
  helpers/index.js
Labels: bug, improvement
