Repository jsdcommunity/build_Together_Freelacing-site-for-Developers_BackEnd, pull requests merged in 2021-10, with the labels that each got.

#1 Express-boilerplate: Created error handler middleware and basic router setup
  README.md
  app.js
  config/config.env
  controllers/adminControllers.js
  controllers/buyerControllers.js
  controllers/developerControllers.js
  controllers/index.js
  controllers/sampleControllers.js
  helpers/adminHelpers.js
  helpers/buyerHelpers.js
  helpers/developerHelpers.js
  helpers/index.js
  middlewares/errorHandler.js
  package-lock.json
  routes/admin.js
  routes/buyer.js
  routes/developer.js
  routes/index.js
  routes/sample.js
  utils/ErrorResponse.js
Labels: in-review

#3 Verification email send
  config/config.env
  controllers/index.js
  helpers/index.js
  index.js
  middlewares/validations/userValidation.js
  models/user.js
  package.json
  routes/index.js
  utils/email-templates/confirm-email.html
  yarn.lock
Labels: in-review, awaiting-review

#4 Fixed logic error
  models/user.js
Labels: bug

#6 Resolves #5
  models/user.js
Labels: bug

#8 Login route
  controllers/index.js
  helpers/index.js
  middlewares/errorHandler.js
  routes/index.js
Labels: enhancement, in-review, awaiting-review
